import { defineConfig } from 'orval'

export default defineConfig({
  screenApi: {
    output: {
      workspace: 'src/packages/openapi/generated',
      mode: 'tags',
      target: './services',
      schemas: './models',
      indexFiles: true,
      client: 'react-query',
      mock: {
        type: 'msw',
        delay: 10, // 10ms to speed up unit tests
        useExamples: true,
      },
      prettier: true,
      tslint: true,
      clean: true,
      override: {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        header: (info: any /*InfoObject */) => [
          'Generated by orval 🍺',
          'Do not edit manually.',
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
        ],
        mutator: {
          path: '../axios/useApiAxios.ts',
          name: 'useApiAxios',
        },
        query: {
          useQuery: true,
        },
      },
    },
    input: {
      target: './src/packages/openapi/spec/screenApi.v1.yaml',
    },
  },
})
