packages:
  - apps/*
  - packages/*
  - docs/*

catalog:
  '@hookform/resolvers': ^3.9.1
  '@redocly/cli': ^1.34.4
  '@tanstack/react-query': ^5.67.3
  '@tanstack/react-router': ^1.131.8
  '@tanstack/router-plugin': ^1.131.8
  concurrently: ^9.2.0
  lint-staged: ^16.1.5
  lucide-react: ^0.469.0
  orval: ^7.11.2
  prettier: ^3.6.2
  react-hook-form: ^7.62.0
  ts-pattern: ^5.8.0
  typescript: ~5.6.3
  yup: ^1.4.0

catalogs:
  eslint:
    '@eslint/js': ^9.33.0
    '@tanstack/eslint-plugin-query': ^5.83.1
    eslint: ^9.33.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-import: ^2.32.0
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    eslint-plugin-storybook: ^9.1.1
    globals: ^16.3.0
    typescript-eslint: ^8.39.1
  prettier:
    prettier: ^3.6.2
    prettier-plugin-organize-imports: ^4.2.0
    prettier-plugin-tailwindcss: ^0.6.14
  react18:
    '@types/react': ^18.3.17
    '@types/react-dom': ^18.3.5
    react: ^18.3.1
    react-dom: ^18.3.1
  react19:
    '@types/react': ^19.1.10
    '@types/react-dom': ^19.1.7
    react: ^19.1.1
    react-dom: ^19.1.1
  tailwindcss3:
    '@tailwindcss/typography': ^0.5.16
    autoprefixer: ^10.4.20
    eslint-plugin-tailwindcss: ^3.18.0
    postcss: ^8.5.6
    postcss-import: ^16.1.0
    tailwind-merge: ^2.6.0
    tailwindcss: ^3.4.17
    tailwindcss-animate: ^1.0.7
  unittesting:
    '@testing-library/jest-dom': ^6.7.0
    '@testing-library/react': ^16.3.0
    '@testing-library/user-event': ^14.6.1
    vitest-localstorage-mock: ^0.1.2
    vitest-location-mock: ^1.0.4
    vitest-mock-axios: ^0.1.0
  vite:
    '@vitejs/plugin-react': ^5.0.0
    '@vitest/coverage-istanbul': ^3.2.4
    '@vitest/ui': ^3.2.4
    vite: ^7.1.2
    vite-plugin-dts: ^4.5.3
    vite-plugin-lib-inject-css: ^2.2.1
    vite-tsconfig-paths: ^5.1.4
    vitest: ^3.2.4

ignoredBuiltDependencies:
  - '@swc/core'
  - core-js
  - esbuild
  - protobufjs

onlyBuiltDependencies:
  - msw
