packages:
  - apps/*
  - packages/*
  - docs/*

catalog:
  "@redocly/cli": ^1.34.4
  "@vitest/coverage-istanbul": 3.0.5
  "@vitest/ui": 3.0.5
  eslint: "^9.17.0"
  prettier: "^3.4.2"
  orval: "^7.5.0"
  typescript: ~5.6.2
  vite: ^6.0.3
  vitest: ^3.0.5

catalogs:
  react18:
    "@types/react": "^18.3.17"
    "@types/react-dom": "^18.3.5"
    react: ^18.3.1
    react-dom: ^18.3.1
  tailwindcss3:
    "@tailwindcss/typography": ^0.5.16
    "eslint-plugin-tailwindcss": ^3.18.0
    autoprefixer: ^10.4.20
    postcss: ^8.4.49
    "postcss-import": "^16.1.0"
    tailwindcss: ^3.4.17
    "tailwindcss-animate": "^1.0.7"
  tailwindcss4:
    "@tailwindcss/postcss": "^4.0.6"
    "@tailwindcss/typography": "^0.5.16"
    "@tailwindcss/vite": "^4.0.6"
    tailwindcss: "^4.0.6"
