packages:
  - apps/*
  - packages/*
  - docs/*

catalog:
  '@hookform/resolvers': ^3.9.1
  '@redocly/cli': ^1.34.4
  '@tanstack/eslint-plugin-query': ^5.67.3
  '@tanstack/react-query': ^5.67.3
  '@tanstack/react-router': ^1.128.4
  '@tanstack/router-plugin': ^1.128.4
  '@vitejs/plugin-react': ^4.3.4
  '@vitest/coverage-istanbul': ^3.0.7
  '@vitest/ui': ^3.0.7
  concurrently: ^9.2.0
  eslint: ^9.17.0
  lint-staged: ^15.5.2
  lucide-react: ^0.469.0
  orval: ^7.5.0
  prettier: ^3.4.2
  typescript: ~5.6.3
  vite: ^6.2.0
  vite-plugin-lib-inject-css: ^2.2.1
  vitest: ^3.2.4
  yup: ^1.4.0

catalogs:
  react18:
    '@types/react': ^18.3.17
    '@types/react-dom': ^18.3.5
    react: ^18.3.1
    react-dom: ^18.3.1
    react-hook-form: ^7.54.2
  tailwindcss3:
    '@tailwindcss/typography': ^0.5.16
    autoprefixer: ^10.4.20
    eslint-plugin-tailwindcss: ^3.18.0
    postcss: ^8.5.6
    postcss-import: ^16.1.0
    tailwind-merge: ^2.6.0
    tailwindcss: ^3.4.17
    tailwindcss-animate: ^1.0.7

ignoredBuiltDependencies:
  - '@swc/core'
  - core-js
  - esbuild
  - protobufjs

onlyBuiltDependencies:
  - msw
