/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * screen-geometry-app-backend-serverless-apis-v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  type QueryFunction,
  type QueryKey,
  type UseQueryOptions,
  type UseQueryResult,
} from '@tanstack/react-query'
import type { ErrorResponse } from '../../../generated/openapi/models'
import type { DataBaseEntry } from '../../../models/Database'
import useApiAxios from '../useApiAxios'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

export const useSearchListActionHook = () => {
  const searchListAction = useApiAxios<Array<DataBaseEntry>>()

  return (signal?: AbortSignal) => {
    return searchListAction({ url: '/db/monitor.json', baseURL: '', method: 'get', signal })
  }
}

export const getSearchListActionQueryKey = () => ['/searchlist'] as const

export const useSearchListActionQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useSearchListActionHook>>>,
  TError = ErrorResponse,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchListActionHook>>>, TError, TData>
}): UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchListActionHook>>>, TError, TData> & {
  queryKey: QueryKey
} => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getSearchListActionQueryKey()

  const listScreensAction = useSearchListActionHook()

  const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useSearchListActionHook>>>> = ({ signal }) =>
    listScreensAction(signal)

  return { queryKey, queryFn, ...queryOptions }
}

export type SearchListActionQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSearchListActionHook>>>>
export type SearchListActionQueryError = ErrorResponse

export const useSearchListAction = <
  TData = Awaited<ReturnType<ReturnType<typeof useSearchListActionHook>>>,
  TError = ErrorResponse,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchListActionHook>>>, TError, TData>
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = useSearchListActionQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}
