openapi: "3.0.1"
info:
  title: "screen-geometry-app-backend-serverless-apis-v1"
  version: "1.0.0"
servers:
  - url: "https://{environment}.typicode.com:{port}/{path}"
    variables:
      environment:
        default: jsonplaceholder
        enum:
          - jsonplaceholder
          - api
          - dev
          - staging
      port:
        enum:
          - '443'
          - '8443'
        default: '443'
      path:
        default: "v1"
        enum:
          - "v1"
paths:
  /screens:
    get:
      tags:
        - "screen list service"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScreenListResponse"
        "400":
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: "401 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "403 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "408":
          description: "408 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "415":
          description: "415 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "429":
          description: "429 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "503":
          description: "503 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - authorizer-api-v2: []
        - api_key: []
      operationId: "listScreensAction"
  /screens/create:
    post:
      tags:
        - "screen list service"
      requestBody:
        description: Primitive for generating a ScreenItem object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScreenInput'
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScreenItemRespose"
        "400":
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: "401 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "403 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "408":
          description: "408 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "415":
          description: "415 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "429":
          description: "429 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "503":
          description: "503 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - authorizer-api-v2: []
        - api_key: []
      operationId: "createScreenAction"
    options:
      tags:
        - "screen list service"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
      operationId: "optionsScreenListAction"
  /screens/{id}/favorite:
    patch:
      tags:
        - "screen action service"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScreenItemRespose"
        "400":
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: "401 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "403 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "408":
          description: "408 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "415":
          description: "415 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "429":
          description: "429 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "503":
          description: "503 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - authorizer-api-v2: []
        - api_key: []
      operationId: "favoriteScreenAction"
    options:
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
      operationId: "optionsFavoriteScreenAction"
  /screens/{id}:
    get:
      tags:
        - "screen service"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScreenListResponse"
        "400":
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: "401 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "403 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "408":
          description: "408 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "415":
          description: "415 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "429":
          description: "429 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "503":
          description: "503 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - authorizer-api-v1: []
        - api_key: []
      operationId: findScreenAction"
    put:
      tags:
        - "screen service"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent screen in list
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScreenItem'
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScreenItemRespose"
        "400":
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: "401 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "403 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "408":
          description: "408 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "415":
          description: "415 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "429":
          description: "429 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "503":
          description: "503 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - authorizer-api-v1: []
        - api_key: []
      operationId: "updateScreenAction"
    delete:
      tags:
        - "screen service"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScreenIdResponse"
        "400":
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: "401 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "403 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "408":
          description: "408 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "415":
          description: "415 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "429":
          description: "429 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "503":
          description: "503 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - authorizer-api-v1: []
        - api_key: []
      operationId: "deleteScreenAction"
    options:
      tags:
        - "screen service"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
      operationId: "optionsScreenAction"
components:
  schemas:
    ScreenListResponse:
      required:
        - "list"
      type: object
      properties:
        list:
          type: array
          items:
            $ref: "#/components/schemas/ScreenItem"
    ScreenIdResponse:
      required:
        - "id"
      type: object
      properties:
        id:
          type: string
    ScreenItemRespose:
      required:
        - "item"
      type: object
      properties:
        item:
          $ref: "#/components/schemas/ScreenItem"
    ScreenItem:
      required:
        - "id"
        - "tag"
        - "data"
        - "favorite"
      type: object
      properties:
        id:
          type: string
          minLength: 1
        favorite:
          type: boolean
        tag:
          $ref: "#/components/schemas/ScreenInput"
        data:
          $ref: "#/components/schemas/ScreenData"
        spec:
          $ref: "#/components/schemas/ScreenSpec"
        render:
          $ref: "#/components/schemas/ScreenRender"
      description: "Complete screen object"
    ScreenInput:
      required:
        - "diagonalSize"
        - "aspectRatio"
      type: object
      properties:
        diagonalSize:
          type: number
          minimum: 0
          exclusiveMinimum: true
        aspectRatio:
          minLength: 3
          type: string
        hRes:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        vRes:
          type: number
      description: "Screen primitive data"
    ScreenData:
      required:
        - "hSize"
        - "vSize"
        - "hAspectRatio"
        - "vAspectRatio"
      type: object
      properties:
        hSize:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        vSize:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        hAspectRatio:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        vAspectRatio:
          type: integer
          minimum: 0
          exclusiveMinimum: true
      description: "Screen physical characteristics"
    ScreenSpec:
      required:
        - "hRes"
        - "vRes"
        - "ppi"
      type: object
      properties:
        hRes:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        vRes:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        ppi:
          type: number
          minimum: 0
          exclusiveMinimum: true
      description: "Screen resolution characteristics"
    ScreenRender:
      required:
        - "width"
        - "height"
        - "color"
      type: object
      properties:
        width:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        height:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        pixelSize:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        color:
          $ref: "#/components/schemas/ScreenColor"
      description: "Screen representation in UI"
    ScreenColor:
      required:
        - "r"
        - "g"
        - "b"
      type: object
      properties:
        r:
          type: integer
          minimum: 0
          exclusiveMinimum: false
          maximum: 255
          exclusiveMaximum: false
        g:
          type: integer
          minimum: 0
          exclusiveMinimum: false
          maximum: 255
          exclusiveMaximum: false
        b:
          type: integer
          minimum: 0
          exclusiveMinimum: false
          maximum: 255
          exclusiveMaximum: false
      description: "Screen representation color"
    ErrorResponse:
      required:
      - "error"
      type: object
      properties:
        error:
          required:
          - "code"
          - "status"
          type: object
          properties:
            code:
              type: number
            message:
              minLength: 1
              type: string
            status:
              minLength: 1
              type: string
            details:
              type: object
              properties:
                reason:
                  minLength: 1
                  type: string
                domain:
                  minLength: 1
                  type: string
                metadata:
                  type: object
      description: ""
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
    authorizer-api-v1:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "custom"
x-amazon-apigateway-policy:
  Version: "1.0.0"
  Statement:
    - Effect: "Allow"
      Principal: "*"
      Action: "execute-api:Invoke"
      Resource: "arn:aws:execute-api:ap-southeast-1:123456789012:abcdefabcd/*/*/*"
