type: object
required:
  - ENV_TYPE
  - SERVER_API_URL
  - GA_TRACKING_ID
properties:
  ENV_TYPE:
    type: string
    description: deployment environment type
  SERVER_API_URL:
    type: string
    description: server API URL
  GA_TRACKING_ID:
    type: string
    description: Google Analytics Tracking ID
