/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './app/routes/__root'

// Create Virtual Routes

const ScreensLazyImport = createFileRoute('/screens')()
const HelpLazyImport = createFileRoute('/help')()
const ContactLazyImport = createFileRoute('/contact')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ScreensLazyRoute = ScreensLazyImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./app/routes/screens.lazy').then((d) => d.Route))

const HelpLazyRoute = HelpLazyImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./app/routes/help.lazy').then((d) => d.Route))

const ContactLazyRoute = ContactLazyImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./app/routes/contact.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./app/routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyImport
      parentRoute: typeof rootRoute
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpLazyImport
      parentRoute: typeof rootRoute
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRoute
  '/help': typeof HelpLazyRoute
  '/screens': typeof ScreensLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRoute
  '/help': typeof HelpLazyRoute
  '/screens': typeof ScreensLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRoute
  '/help': typeof HelpLazyRoute
  '/screens': typeof ScreensLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/help' | '/screens'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/help' | '/screens'
  id: '__root__' | '/' | '/contact' | '/help' | '/screens'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ContactLazyRoute: typeof ContactLazyRoute
  HelpLazyRoute: typeof HelpLazyRoute
  ScreensLazyRoute: typeof ScreensLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ContactLazyRoute: ContactLazyRoute,
  HelpLazyRoute: HelpLazyRoute,
  ScreensLazyRoute: ScreensLazyRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contact",
        "/help",
        "/screens"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/contact": {
      "filePath": "contact.lazy.tsx"
    },
    "/help": {
      "filePath": "help.lazy.tsx"
    },
    "/screens": {
      "filePath": "screens.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
