import { GetLanguagesQuery } from '@/generated'
import { mockGetLanguagesQueryCountryService } from '@/generated/countries/countries-client.mws'
import { HttpResponse } from 'msw'

export const getGetLanguagesResponseMock = () => {
  return {
    languages: [
      {
        code: 'af',
        name: 'Afrikaans',
        native: 'Afrikaans',
        rtl: false,
      },
      {
        code: 'am',
        name: 'Amharic',
        native: 'አማርኛ',
        rtl: false,
      },
      {
        code: 'ar',
        name: 'Arabic',
        native: 'العربية',
        rtl: true,
      },
      {
        code: 'ay',
        name: 'Aymara',
        native: 'Aymar',
        rtl: false,
      },
      {
        code: 'az',
        name: 'Azerbaijani',
        native: 'Azərbaycanca / آذربايجان',
        rtl: false,
      },
      {
        code: 'be',
        name: 'Belarusian',
        native: 'Беларуская',
        rtl: false,
      },
      {
        code: 'bg',
        name: 'Bulgarian',
        native: 'Български',
        rtl: false,
      },
      {
        code: 'bi',
        name: 'Bislama',
        native: 'Bislama',
        rtl: false,
      },
      {
        code: 'bn',
        name: 'Bengali',
        native: 'বাংলা',
        rtl: false,
      },
      {
        code: 'bs',
        name: 'Bosnian',
        native: 'Bosanski',
        rtl: false,
      },
      {
        code: 'ca',
        name: 'Catalan',
        native: 'Català',
        rtl: false,
      },
      {
        code: 'ch',
        name: 'Chamorro',
        native: 'Chamoru',
        rtl: false,
      },
      {
        code: 'cs',
        name: 'Czech',
        native: 'Čeština',
        rtl: false,
      },
      {
        code: 'da',
        name: 'Danish',
        native: 'Dansk',
        rtl: false,
      },
      {
        code: 'de',
        name: 'German',
        native: 'Deutsch',
        rtl: false,
      },
      {
        code: 'dv',
        name: 'Divehi',
        native: 'ދިވެހިބަސް',
        rtl: true,
      },
      {
        code: 'dz',
        name: 'Dzongkha',
        native: 'ཇོང་ཁ',
        rtl: false,
      },
      {
        code: 'el',
        name: 'Greek',
        native: 'Ελληνικά',
        rtl: false,
      },
      {
        code: 'en',
        name: 'English',
        native: 'English',
        rtl: false,
      },
      {
        code: 'es',
        name: 'Spanish',
        native: 'Español',
        rtl: false,
      },
      {
        code: 'et',
        name: 'Estonian',
        native: 'Eesti',
        rtl: false,
      },
      {
        code: 'eu',
        name: 'Basque',
        native: 'Euskara',
        rtl: false,
      },
      {
        code: 'fa',
        name: 'Persian',
        native: 'فارسی',
        rtl: true,
      },
      {
        code: 'ff',
        name: 'Peul',
        native: 'Fulfulde',
        rtl: false,
      },
      {
        code: 'fi',
        name: 'Finnish',
        native: 'Suomi',
        rtl: false,
      },
      {
        code: 'fj',
        name: 'Fijian',
        native: 'Na Vosa Vakaviti',
        rtl: false,
      },
      {
        code: 'fo',
        name: 'Faroese',
        native: 'Føroyskt',
        rtl: false,
      },
      {
        code: 'fr',
        name: 'French',
        native: 'Français',
        rtl: false,
      },
      {
        code: 'ga',
        name: 'Irish',
        native: 'Gaeilge',
        rtl: false,
      },
      {
        code: 'gl',
        name: 'Galician',
        native: 'Galego',
        rtl: false,
      },
      {
        code: 'gn',
        name: 'Guarani',
        native: "Avañe'ẽ",
        rtl: false,
      },
      {
        code: 'gv',
        name: 'Manx',
        native: 'Gaelg',
        rtl: false,
      },
      {
        code: 'he',
        name: 'Hebrew',
        native: 'עברית',
        rtl: true,
      },
      {
        code: 'hi',
        name: 'Hindi',
        native: 'हिन्दी',
        rtl: false,
      },
      {
        code: 'hr',
        name: 'Croatian',
        native: 'Hrvatski',
        rtl: false,
      },
      {
        code: 'ht',
        name: 'Haitian',
        native: 'Krèyol ayisyen',
        rtl: false,
      },
      {
        code: 'hu',
        name: 'Hungarian',
        native: 'Magyar',
        rtl: false,
      },
      {
        code: 'hy',
        name: 'Armenian',
        native: 'Հայերեն',
        rtl: false,
      },
      {
        code: 'id',
        name: 'Indonesian',
        native: 'Bahasa Indonesia',
        rtl: false,
      },
      {
        code: 'is',
        name: 'Icelandic',
        native: 'Íslenska',
        rtl: false,
      },
      {
        code: 'it',
        name: 'Italian',
        native: 'Italiano',
        rtl: false,
      },
      {
        code: 'ja',
        name: 'Japanese',
        native: '日本語',
        rtl: false,
      },
      {
        code: 'ka',
        name: 'Georgian',
        native: 'ქართული',
        rtl: false,
      },
      {
        code: 'kg',
        name: 'Kongo',
        native: 'KiKongo',
        rtl: false,
      },
      {
        code: 'kk',
        name: 'Kazakh',
        native: 'Қазақша',
        rtl: false,
      },
      {
        code: 'kl',
        name: 'Greenlandic',
        native: 'Kalaallisut',
        rtl: false,
      },
      {
        code: 'km',
        name: 'Cambodian',
        native: 'ភាសាខ្មែរ',
        rtl: false,
      },
      {
        code: 'ko',
        name: 'Korean',
        native: '한국어',
        rtl: false,
      },
      {
        code: 'ku',
        name: 'Kurdish',
        native: 'Kurdî / كوردی',
        rtl: true,
      },
      {
        code: 'ky',
        name: 'Kyrgyz',
        native: 'Кыргызча',
        rtl: false,
      },
      {
        code: 'la',
        name: 'Latin',
        native: 'Latina',
        rtl: false,
      },
      {
        code: 'lb',
        name: 'Luxembourgish',
        native: 'Lëtzebuergesch',
        rtl: false,
      },
      {
        code: 'ln',
        name: 'Lingala',
        native: 'Lingála',
        rtl: false,
      },
      {
        code: 'lo',
        name: 'Laotian',
        native: 'ລາວ / Pha xa lao',
        rtl: false,
      },
      {
        code: 'lt',
        name: 'Lithuanian',
        native: 'Lietuvių',
        rtl: false,
      },
      {
        code: 'lu',
        name: 'Luba-Katanga',
        native: 'Tshiluba',
        rtl: false,
      },
      {
        code: 'lv',
        name: 'Latvian',
        native: 'Latviešu',
        rtl: false,
      },
      {
        code: 'mg',
        name: 'Malagasy',
        native: 'Malagasy',
        rtl: false,
      },
      {
        code: 'mh',
        name: 'Marshallese',
        native: 'Kajin Majel / Ebon',
        rtl: false,
      },
      {
        code: 'mi',
        name: 'Maori',
        native: 'Māori',
        rtl: false,
      },
      {
        code: 'mk',
        name: 'Macedonian',
        native: 'Македонски',
        rtl: false,
      },
      {
        code: 'mn',
        name: 'Mongolian',
        native: 'Монгол',
        rtl: false,
      },
      {
        code: 'ms',
        name: 'Malay',
        native: 'Bahasa Melayu',
        rtl: false,
      },
      {
        code: 'mt',
        name: 'Maltese',
        native: 'bil-Malti',
        rtl: false,
      },
      {
        code: 'my',
        name: 'Burmese',
        native: 'မြန်မာစာ',
        rtl: false,
      },
      {
        code: 'na',
        name: 'Nauruan',
        native: 'Dorerin Naoero',
        rtl: false,
      },
      {
        code: 'nb',
        name: 'Norwegian Bokmål',
        native: 'Norsk bokmål',
        rtl: false,
      },
      {
        code: 'nd',
        name: 'North Ndebele',
        native: 'Sindebele',
        rtl: false,
      },
      {
        code: 'ne',
        name: 'Nepali',
        native: 'नेपाली',
        rtl: false,
      },
      {
        code: 'nl',
        name: 'Dutch',
        native: 'Nederlands',
        rtl: false,
      },
      {
        code: 'nn',
        name: 'Norwegian Nynorsk',
        native: 'Norsk nynorsk',
        rtl: false,
      },
      {
        code: 'no',
        name: 'Norwegian',
        native: 'Norsk',
        rtl: false,
      },
      {
        code: 'nr',
        name: 'South Ndebele',
        native: 'isiNdebele',
        rtl: false,
      },
      {
        code: 'ny',
        name: 'Chichewa',
        native: 'Chi-Chewa',
        rtl: false,
      },
      {
        code: 'oc',
        name: 'Occitan',
        native: 'Occitan',
        rtl: false,
      },
      {
        code: 'pa',
        name: 'Panjabi / Punjabi',
        native: 'ਪੰਜਾਬੀ / पंजाबी / پنجابي',
        rtl: false,
      },
      {
        code: 'pl',
        name: 'Polish',
        native: 'Polski',
        rtl: false,
      },
      {
        code: 'ps',
        name: 'Pashto',
        native: 'پښتو',
        rtl: true,
      },
      {
        code: 'pt',
        name: 'Portuguese',
        native: 'Português',
        rtl: false,
      },
      {
        code: 'qu',
        name: 'Quechua',
        native: 'Runa Simi',
        rtl: false,
      },
      {
        code: 'rn',
        name: 'Kirundi',
        native: 'Kirundi',
        rtl: false,
      },
      {
        code: 'ro',
        name: 'Romanian',
        native: 'Română',
        rtl: false,
      },
      {
        code: 'ru',
        name: 'Russian',
        native: 'Русский',
        rtl: false,
      },
      {
        code: 'rw',
        name: 'Rwandi',
        native: 'Kinyarwandi',
        rtl: false,
      },
      {
        code: 'sg',
        name: 'Sango',
        native: 'Sängö',
        rtl: false,
      },
      {
        code: 'si',
        name: 'Sinhalese',
        native: 'සිංහල',
        rtl: false,
      },
      {
        code: 'sk',
        name: 'Slovak',
        native: 'Slovenčina',
        rtl: false,
      },
      {
        code: 'sl',
        name: 'Slovenian',
        native: 'Slovenščina',
        rtl: false,
      },
      {
        code: 'sm',
        name: 'Samoan',
        native: 'Gagana Samoa',
        rtl: false,
      },
      {
        code: 'sn',
        name: 'Shona',
        native: 'chiShona',
        rtl: false,
      },
      {
        code: 'so',
        name: 'Somalia',
        native: 'Soomaaliga',
        rtl: false,
      },
      {
        code: 'sq',
        name: 'Albanian',
        native: 'Shqip',
        rtl: false,
      },
      {
        code: 'sr',
        name: 'Serbian',
        native: 'Српски',
        rtl: false,
      },
      {
        code: 'ss',
        name: 'Swati',
        native: 'SiSwati',
        rtl: false,
      },
      {
        code: 'st',
        name: 'Southern Sotho',
        native: 'Sesotho',
        rtl: false,
      },
      {
        code: 'sv',
        name: 'Swedish',
        native: 'Svenska',
        rtl: false,
      },
      {
        code: 'sw',
        name: 'Swahili',
        native: 'Kiswahili',
        rtl: false,
      },
      {
        code: 'ta',
        name: 'Tamil',
        native: 'தமிழ்',
        rtl: false,
      },
      {
        code: 'tg',
        name: 'Tajik',
        native: 'Тоҷикӣ',
        rtl: false,
      },
      {
        code: 'th',
        name: 'Thai',
        native: 'ไทย / Phasa Thai',
        rtl: false,
      },
      {
        code: 'ti',
        name: 'Tigrinya',
        native: 'ትግርኛ',
        rtl: false,
      },
      {
        code: 'tk',
        name: 'Turkmen',
        native: 'Туркмен / تركمن',
        rtl: false,
      },
      {
        code: 'tn',
        name: 'Tswana',
        native: 'Setswana',
        rtl: false,
      },
      {
        code: 'to',
        name: 'Tonga',
        native: 'Lea Faka-Tonga',
        rtl: false,
      },
      {
        code: 'tr',
        name: 'Turkish',
        native: 'Türkçe',
        rtl: false,
      },
      {
        code: 'ts',
        name: 'Tsonga',
        native: 'Xitsonga',
        rtl: false,
      },
      {
        code: 'uk',
        name: 'Ukrainian',
        native: 'Українська',
        rtl: false,
      },
      {
        code: 'ur',
        name: 'Urdu',
        native: 'اردو',
        rtl: true,
      },
      {
        code: 'uz',
        name: 'Uzbek',
        native: 'Ўзбек',
        rtl: false,
      },
      {
        code: 've',
        name: 'Venda',
        native: 'Tshivenḓa',
        rtl: false,
      },
      {
        code: 'vi',
        name: 'Vietnamese',
        native: 'Tiếng Việt',
        rtl: false,
      },
      {
        code: 'xh',
        name: 'Xhosa',
        native: 'isiXhosa',
        rtl: false,
      },
      {
        code: 'zh',
        name: 'Chinese',
        native: '中文',
        rtl: false,
      },
      {
        code: 'zu',
        name: 'Zulu',
        native: 'isiZulu',
        rtl: false,
      },
    ],
  }
}

export const getGetLanguagesMockHandler = (overrideResponse?: GetLanguagesQuery) =>
  mockGetLanguagesQueryCountryService(() =>
    HttpResponse.json({
      data: overrideResponse ? overrideResponse : getGetLanguagesResponseMock(),
    })
  )

export const getgetGetLanguagesMock = () => [getGetLanguagesMockHandler()]
