/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './../routes/__root'
import { Route as ShareRouteImport } from './../routes/share'
import { Route as ScreensRouteImport } from './../routes/screens'
import { Route as MyscreensRouteImport } from './../routes/myscreens'

const HelpLazyRouteImport = createFileRoute('/help')()
const ContactLazyRouteImport = createFileRoute('/contact')()
const IndexLazyRouteImport = createFileRoute('/')()

const HelpLazyRoute = HelpLazyRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./../routes/help.lazy').then((d) => d.Route))
const ContactLazyRoute = ContactLazyRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./../routes/contact.lazy').then((d) => d.Route))
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./../routes/share.lazy').then((d) => d.Route))
const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const MyscreensRoute = MyscreensRouteImport.update({
  id: '/myscreens',
  path: '/myscreens',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./../routes/myscreens.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./../routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/myscreens': typeof MyscreensRoute
  '/screens': typeof ScreensRoute
  '/share': typeof ShareRoute
  '/contact': typeof ContactLazyRoute
  '/help': typeof HelpLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/myscreens': typeof MyscreensRoute
  '/screens': typeof ScreensRoute
  '/share': typeof ShareRoute
  '/contact': typeof ContactLazyRoute
  '/help': typeof HelpLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/myscreens': typeof MyscreensRoute
  '/screens': typeof ScreensRoute
  '/share': typeof ShareRoute
  '/contact': typeof ContactLazyRoute
  '/help': typeof HelpLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/myscreens' | '/screens' | '/share' | '/contact' | '/help'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/myscreens' | '/screens' | '/share' | '/contact' | '/help'
  id:
    | '__root__'
    | '/'
    | '/myscreens'
    | '/screens'
    | '/share'
    | '/contact'
    | '/help'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MyscreensRoute: typeof MyscreensRoute
  ScreensRoute: typeof ScreensRoute
  ShareRoute: typeof ShareRoute
  ContactLazyRoute: typeof ContactLazyRoute
  HelpLazyRoute: typeof HelpLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myscreens': {
      id: '/myscreens'
      path: '/myscreens'
      fullPath: '/myscreens'
      preLoaderRoute: typeof MyscreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MyscreensRoute: MyscreensRoute,
  ScreensRoute: ScreensRoute,
  ShareRoute: ShareRoute,
  ContactLazyRoute: ContactLazyRoute,
  HelpLazyRoute: HelpLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
