/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './../routes/__root'
import { Route as ScreensRouteImport } from './../routes/screens'
import { Route as MyscreensRouteImport } from './../routes/myscreens'
import { Route as ShareIndexRouteImport } from './../routes/share/index'

const HelpLazyRouteImport = createFileRoute('/help')()
const ContactLazyRouteImport = createFileRoute('/contact')()
const IndexLazyRouteImport = createFileRoute('/')()
const ShareAllLazyRouteImport = createFileRoute('/share/all')()
const Share32by9LazyRouteImport = createFileRoute('/share/32by9')()
const Share21by9LazyRouteImport = createFileRoute('/share/21by9')()
const Share16by9LazyRouteImport = createFileRoute('/share/16by9')()

const HelpLazyRoute = HelpLazyRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./../routes/help.lazy').then((d) => d.Route))
const ContactLazyRoute = ContactLazyRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./../routes/contact.lazy').then((d) => d.Route))
const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const MyscreensRoute = MyscreensRouteImport.update({
  id: '/myscreens',
  path: '/myscreens',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./../routes/myscreens.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./../routes/index.lazy').then((d) => d.Route))
const ShareIndexRoute = ShareIndexRouteImport.update({
  id: '/share/',
  path: '/share/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../routes/share/index.lazy').then((d) => d.Route),
)
const ShareAllLazyRoute = ShareAllLazyRouteImport.update({
  id: '/share/all',
  path: '/share/all',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./../routes/share/all.lazy').then((d) => d.Route))
const Share32by9LazyRoute = Share32by9LazyRouteImport.update({
  id: '/share/32by9',
  path: '/share/32by9',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../routes/share/32by9.lazy').then((d) => d.Route),
)
const Share21by9LazyRoute = Share21by9LazyRouteImport.update({
  id: '/share/21by9',
  path: '/share/21by9',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../routes/share/21by9.lazy').then((d) => d.Route),
)
const Share16by9LazyRoute = Share16by9LazyRouteImport.update({
  id: '/share/16by9',
  path: '/share/16by9',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../routes/share/16by9.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/myscreens': typeof MyscreensRoute
  '/screens': typeof ScreensRoute
  '/contact': typeof ContactLazyRoute
  '/help': typeof HelpLazyRoute
  '/share/16by9': typeof Share16by9LazyRoute
  '/share/21by9': typeof Share21by9LazyRoute
  '/share/32by9': typeof Share32by9LazyRoute
  '/share/all': typeof ShareAllLazyRoute
  '/share/': typeof ShareIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/myscreens': typeof MyscreensRoute
  '/screens': typeof ScreensRoute
  '/contact': typeof ContactLazyRoute
  '/help': typeof HelpLazyRoute
  '/share/16by9': typeof Share16by9LazyRoute
  '/share/21by9': typeof Share21by9LazyRoute
  '/share/32by9': typeof Share32by9LazyRoute
  '/share/all': typeof ShareAllLazyRoute
  '/share': typeof ShareIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/myscreens': typeof MyscreensRoute
  '/screens': typeof ScreensRoute
  '/contact': typeof ContactLazyRoute
  '/help': typeof HelpLazyRoute
  '/share/16by9': typeof Share16by9LazyRoute
  '/share/21by9': typeof Share21by9LazyRoute
  '/share/32by9': typeof Share32by9LazyRoute
  '/share/all': typeof ShareAllLazyRoute
  '/share/': typeof ShareIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/myscreens'
    | '/screens'
    | '/contact'
    | '/help'
    | '/share/16by9'
    | '/share/21by9'
    | '/share/32by9'
    | '/share/all'
    | '/share/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/myscreens'
    | '/screens'
    | '/contact'
    | '/help'
    | '/share/16by9'
    | '/share/21by9'
    | '/share/32by9'
    | '/share/all'
    | '/share'
  id:
    | '__root__'
    | '/'
    | '/myscreens'
    | '/screens'
    | '/contact'
    | '/help'
    | '/share/16by9'
    | '/share/21by9'
    | '/share/32by9'
    | '/share/all'
    | '/share/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MyscreensRoute: typeof MyscreensRoute
  ScreensRoute: typeof ScreensRoute
  ContactLazyRoute: typeof ContactLazyRoute
  HelpLazyRoute: typeof HelpLazyRoute
  Share16by9LazyRoute: typeof Share16by9LazyRoute
  Share21by9LazyRoute: typeof Share21by9LazyRoute
  Share32by9LazyRoute: typeof Share32by9LazyRoute
  ShareAllLazyRoute: typeof ShareAllLazyRoute
  ShareIndexRoute: typeof ShareIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myscreens': {
      id: '/myscreens'
      path: '/myscreens'
      fullPath: '/myscreens'
      preLoaderRoute: typeof MyscreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/': {
      id: '/share/'
      path: '/share'
      fullPath: '/share/'
      preLoaderRoute: typeof ShareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/all': {
      id: '/share/all'
      path: '/share/all'
      fullPath: '/share/all'
      preLoaderRoute: typeof ShareAllLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/32by9': {
      id: '/share/32by9'
      path: '/share/32by9'
      fullPath: '/share/32by9'
      preLoaderRoute: typeof Share32by9LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/21by9': {
      id: '/share/21by9'
      path: '/share/21by9'
      fullPath: '/share/21by9'
      preLoaderRoute: typeof Share21by9LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/16by9': {
      id: '/share/16by9'
      path: '/share/16by9'
      fullPath: '/share/16by9'
      preLoaderRoute: typeof Share16by9LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MyscreensRoute: MyscreensRoute,
  ScreensRoute: ScreensRoute,
  ContactLazyRoute: ContactLazyRoute,
  HelpLazyRoute: HelpLazyRoute,
  Share16by9LazyRoute: Share16by9LazyRoute,
  Share21by9LazyRoute: Share21by9LazyRoute,
  Share32by9LazyRoute: Share32by9LazyRoute,
  ShareAllLazyRoute: ShareAllLazyRoute,
  ShareIndexRoute: ShareIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
